# Generated by Django 5.1.7 on 2025-04-05 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Escribe un título llamativo para tu publicación', max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(help_text='Desarrolla el contenido de tu publicación', verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, help_text='Sube una imagen relacionada con tu publicación', null=True, upload_to='publicaciones/%Y/%m/%d/', verbose_name='Imagen destacada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
